project_id = "bfrtyuzcnpukcjncgawx"

[functions.consume-credit]
verify_jwt = false

[functions.create-pix-payment]
verify_jwt = false

[functions.check-payment-status]
verify_jwt = false

[functions.mercadopago-webhook]
verify_jwt = false
